import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex min-h-screen w-full flex-col bg-space-cadet text-isabelline">
        <div className="grid grid-flow-row grid-cols-3 items-center px-8">
          <div className="col-span-2 flex flex-wrap space-x-2 p-4 font-rampart-one text-8xl font-bold">
            <h1 className="">The</h1>
            <h1 className="">Quick</h1>
            <h1 className="">Brown</h1>
            <h1 className="">Fox</h1>
            <h1 className="pl-4 pt-8 text-3xl">おはよう!!!</h1>
          </div>

          <img src="/fox-animated-1.gif" className="h-1/2 w-full object-cover object-bottom" style={{ imageRendering: "pixelated" }} />
        </div>
      </div>
    </>
  );
};

export default Home;
